services:
   flightapp:
     image: mysql:9.0.1
     container_name: flightapp
     restart: always
     environment:
       MYSQL_USER: root
       MYSQL_ROOT_PASSWORD: root
     ports:
       - "3308:3306"
   adminer:
     image: adminer
     container_name: adminer
     restart: always
     ports:
       - "8183:8080"

